Public Class Constantes
    Public Const PATH_PRODUCTS = "Resources\Products\"
    Public Const PATH_CATEGORIES = "Resources\Categories\"
    Public Const ERROR_COPY = "No se ha podido guardar la imagen seleccionada."
    Public Const ERROR_TITLE = "Error"
    Public Const WARNING_DELETE = "Advertencia"
    Public Const MESSAGE_DELETE_PRODUCT = "Seguro que quieres eliminar este elemento?"
    Public Const MESSAGE_ERROR_UPDATE = "Error al guardar verifica que todos los campos obligatorios estan llenos."
    Public Const FORMAT_PRICE = "0.00 €"
    Public Const INPUT_AMOUNT = "Seleccione la nueva cantidad."
    Public Const ERROR_AMOUNT = "Cantidad seleccionada no valida."
    Public Const NO_RESOULT = "No se han encontrado resultados."
    Public Const NO_ITEMS = "No hay productos que cobrar."
    Public Const FILTER = "Enabled = 'True'"
    Public Const PATH_CONFIG = "Resources\Configuracion"
    Public Const FILE_CONFIG = "Resources\Configuracion\config.json"
    Public Const PATH_RESOURCES = "Resources"
    Public Const ERROR_CONFIG = "Se ha producido un error al guardar."
    Public Const MESSAGE_EXIT_WITH_CHANGES = "Hay cambios sin guardad, si sales no se guardarán, quieres salir?"
    Public Const MESSAGE_PRINT = "Quieres sacar el ticket?"
    Public Const MESSAGE_NO_TICKET = "No hay tickets que cerrar."
    Public Const MESSAGE_TICKETS_PARADOS = "Hay tickets parados, no puedes cerrar caja."
    Public Const MESSAGE_ERROR_CONFIG = "Hay campos no validos."
    Public Const MESSAGE_OBLIGATORY_FIELD = "Este campo es obligatorio"
    Public Const MESSAGE_DUPLICATED_FIELD = "Este codigo ya esta presente en otro producto."
    Public Const MESSAGE_NO_VALID_PRICE = "Precio no valido, tiene que ser superior a 0"
    Public Const MESSAGE_NO_VALID_IVA = "Porcentaje de iva no valido, tiene que ser un valor entre 0 y 99"
    Public Const REGULARIZACION_VENTA = "Producto vendido."
End Class
